bug: now enableAvatarLODs is acting to changes
decentraland/unity-renderer pull request #1097
Opened 2021-08-30 14:33 UTC by AjimenezDCL

When using the URL_PARAM, the  `KernelConfig`  arrives for the first time with the proper value. 
When using the real feature flag takes, `KernelConfig` is sent with default values while the flag value are retrieved.

AvatarLODS where using only the first value that arrived to `KernelConfig`.

To Test:

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2021-08-30 16:35 UTC, BrianAmadori commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/AvatarsLODController.cs
> +            if (enabled == config.features.enableBuilderInWorld)
`enableBuilderInWorld`???

2021-08-30 17:27 UTC, pravusjif commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/AvatarsLODController.cs
> +            if (enabled == config.features.enableBuilderInWorld)
XD WTF

2021-08-30 17:28 UTC, pravusjif requested changes
The change works fine but let's address the `enableBuilderInWorld` usage

2021-08-30 18:49 UTC, AjimenezDCL commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/AvatarsLODController.cs
> +            if (enabled == config.features.enableBuilderInWorld)
Oopsie hahaha

2021-08-31 15:49 UTC, BrianAmadori approved these changes

2021-09-01 18:50 UTC, pravusjif approved these changes

2021-09-02 07:17 UTC, merged