chore: toggle non animator meshes animation with mesh visibility
decentraland/unity-renderer pull request #1811
Opened 2022-01-20 23:30 UTC by pravusjif

**WHY**
Currently when a GLTFShape visibility is changed, if it has an Animation, it always keeps being animated. For example if a mesh visibility is turned off, its animation keeps animating unnecessarily.

This should only apply to meshes on entities that don't have an Animator component (since in those cases the parcel devs don't have control over the animations so they wouldn't care of its state).

**WHAT**
Added Animation to MeshesInfo and added animation toggling on mesh visibility toggling, only for entities that don't have an Animator component.

2022-01-21 00:19 UTC, BrianAmadori requested changes
I think we should add some tests to validate this behaviour keeps working in the future.

2022-01-24 10:11 UTC, Suduck approved these changes
Codewise looks good

2022-02-28 08:16 UTC, davidejensen approved these changes

2022-04-14 21:33 UTC, BrianAmadori approved these changes

2022-04-14 21:57 UTC, merged