fix: main player comms reported rotation
decentraland/unity-renderer pull request #1817
Opened 2022-01-21 23:26 UTC by pbosio

Fixes #476

WHY
Through comms we always report the CAMERA rotation but we should be reporting the CHARACTER rotation, otherwise when players are using the third person camera, they think the rest of the users see them in the direction they point their avatar but they actually see the rotation of the camera...

kernel PR need to be merged first: https://github.com/decentraland/kernel/pull/181

2022-01-24 13:32 UTC, BrianAmadori requested changes

2022-01-24 13:32 UTC, BrianAmadori commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
> +            DCL.Interface.WebInterface.ReportPosition(reportPosition, compositeRotation, playerHeight, cameraRotation);
Please add some tests to avoid future regressions, as this change already broke the client in the past.

2022-01-25 10:09 UTC, AjimenezDCL approved these changes

2022-01-26 22:08 UTC, kuruk-mm commented
This PR fix https://github.com/decentraland/unity-renderer/issues/1822

2022-01-26 23:10 UTC, BrianAmadori approved these changes

2022-01-26 23:10 UTC, merged