feat: improve scene metrics implementation + add offenders tool
decentraland/unity-renderer pull request #1861
Opened 2022-01-28 23:43 UTC by BrianAmadori

## What does this PR change?

...

## How to test the changes?

1. Go to: https://play.decentraland.zone/?renderer-branch={branch_name}&{desired_url_params}
2. ...

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2022-02-10 09:15 UTC, AjimenezDCL approved these changes
I left a couple of comments but I'm approving, good job!

2022-02-14 19:17 UTC, BrianAmadori commented on unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/Variables/BaseHashSet.cs
> +
Why? `Add` shouldn't be modifying the original HashSet enumerable, unless we do `Add( hashSet.Get() )` but that would be silly.

2022-02-16 15:39 UTC, pravusjif requested changes
Excellent job!

The only problem with this branch is something related to the global avatars scene that makes the world not render any avatar, it looks like an easy fix though
![Screen Shot 2022-02-16 at 12 32 27](https://user-images.githubusercontent.com/1031741/154298862-09ccb0cb-d994-45a4-8767-b8ba44a56f57.png)

I think that error fucks up other things because the genesis plaza automatic-doors never open and I can't teleport anywhere, I'll try the build after the fix

2022-02-17 15:22 UTC, pravusjif approved these changes
Awsome! the issue has been solved!

2022-02-17 19:02 UTC, merged