chore: different POIs improvements
decentraland/unity-renderer pull request #1932
Opened 2022-02-16 13:25 UTC by davidejensen

## What does this PR change?

Fix #1901
Removes default name POIs, reduces number of characters of title to avoid more than 2 lines of text, centers the POI icon in the square of the parcel

...

## How to test the changes?

1. Go to: https://play.decentraland.zone/?renderer-branch=fix/poi-improvements
2. Verify in the map the changes listed above

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2022-02-18 08:11 UTC, davidejensen commented
Regarding the point "POI star must be printed exactly on top of the coordinates, and not displaced depending of the text" we need to discuss it @olavra 
I've applied those changes but there are some problems with it, before the star was placed in the geometrical center of the group of parcels with the same name, now I calculate the most centered parcel of the group and center it there, i don't know if that's the expected behavior

2022-03-14 14:22 UTC, davidejensen commented
Can be reviewed, changes have been approved

2022-03-14 15:47 UTC, lorux0 requested changes

2022-03-14 15:47 UTC, lorux0 commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.cs
> +            if (sceneInfo.name != null && sceneInfo.name.Equals(EMPTY_PARCEL_NAME))
could you extract into a method: `IsAnEmptyParcel`

2022-03-14 15:47 UTC, lorux0 commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.cs
> +            foreach (var parcel in sceneInfo.parcels)
you can extract this block into a method in `MinimapMetadata`: `GetNearestParcel(Vector2 from)`

2022-03-14 15:48 UTC, lorux0 approved these changes

2022-03-15 10:02 UTC, merged