Feat: UI loading wheel
decentraland/unity-renderer pull request #2268
Opened 2022-05-06 11:54 UTC by JuanSalice

## What does this PR change?

This PR removes the loading spinner based on sprites, and replaces it with a spinner made with shader graph. New materials where added for the different uses of the spinners.

...

## How to test the changes?

1. Go to: https://play.decentraland.zone/?renderer-branch=feat/UI-Loading-Wheel
2. Open the main menu
3. Verify the correct behaviour of the loading spinners

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2022-05-08 18:09 UTC, sandrade-dcl requested changes
I left some chenage requests.

Apart of them, I would like to add this: Could we move all the loading spinner assets (scripts, materials, animations, shaders, etc.) to `Assets/UIComponents/LoadingSpinnerAssets`? I think it would make more sense to have them in the UI Components folder.

2022-05-08 18:09 UTC, sandrade-dcl commented on unity-renderer/Assets/Rendering/UI/ChargeWheel/UILoadingSpinner.cs
> +            _material = _img.materialForRendering;
Why are you doing here the `new Material` assignation? As I can see, the next instruction is already setting the `_material` variable.

```suggestion
            _material = _img.materialForRendering;
```

2022-05-11 08:34 UTC, sandrade-dcl approved these changes

2022-05-16 15:54 UTC, RominaMarchetti approved these changes

2022-05-16 17:06 UTC, merged