feat: skybox-satellite-planar
decentraland/unity-renderer pull request #2273
Opened 2022-05-06 16:59 UTC by dcl-glb

## What does this PR change?

Two new features for procedural skybox:
- Satellite layer: Any prefab can be used as a satellite and it will render on the secondary camera.
- Planar layer: This layer are specific for particle system prefabs. particle system should be of type circle or hemisphere only. 

## How to test the changes?

1. Go to: https://play.decentraland.zone/?renderer=https://glob-dland-s3-unity-renderer.s3.amazonaws.com/branch/feat/skybox-satellite-planar-horizon

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2022-05-10 17:42 UTC, pravusjif commented on unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/Configuration/Config3DPlanar.cs
> +        public float radius;                    // Need to initialize with particle system prefab's radius
Is this comment needed?

2022-05-10 17:52 UTC, pravusjif commented on unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/Configuration/Config3DSatellite.cs
> +        public float timeSpan_End;
I'd rename these to `timeSpanStart` and `timeSpanEnd`

2022-05-10 17:56 UTC, pravusjif commented on unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/Configuration/SkyboxConfiguration.cs
> +    //[CreateAssetMenu(fileName = "Skybox Configuration", menuName = "ScriptableObjects/SkyboxConfiguration", order = 1)]
Will this be used? otherwise let's remove this commented code

2022-05-10 19:25 UTC, pravusjif commented on unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/Editor/Procedural Skybox/Base Layers/RenderBackgroundColorLayer.cs
> +            EditorGUILayout.LabelField("Horizon Mask", EditorStyles.boldLabel);
if `RenderHorizonLayer()` is called frequently let's cache all these new strings into CONSTs.

2022-05-10 19:28 UTC, pravusjif commented on unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/Editor/Procedural Skybox/Base Layers/RenderHorizonPlane.cs
> +            RenderSimpleValues.RenderTexture("Texture", ref config.horizonPlaneTexture);
if `RenderLayer()` is called frequently let's cache all these new strings into CONSTs. I even see some of them (like `"Texture"`, `"Tiling"`, `"Offset"`) repeated for example in `RenderBackgroundColorLayer.cs`, maybe those (or all) could be in a statically accessible place or config structure.

2022-05-10 21:04 UTC, pravusjif requested changes

2022-05-10 21:04 UTC, pravusjif commented on unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/Editor/Procedural Skybox/Layers3D/RenderSatellite3DLayer.cs
> +                RenderSimpleValues.RenderFloatField("Rotation Speed", ref config.rotateSpeed);
Several of these strings already exist at `unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/Editor/Procedural Skybox/SkyboxEditorLiterals.cs`, you could add the missing ones and reuse the ones that are already there

2022-05-10 21:04 UTC, pravusjif commented on unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/Editor/Procedural Skybox/Layers3D/RenderPlanar3DLayer.cs
> +            RenderSimpleValues.RenderBoolField("Render In Main Camera", ref config.renderWithMainCamera);
Several of these strings already exist at `unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/Editor/Procedural Skybox/SkyboxEditorLiterals.cs`, you could add the missing ones and reuse the ones that are already there

2022-05-10 21:04 UTC, pravusjif commented on unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/Editor/Procedural Skybox/Base Layers/RenderBackgroundColorLayer.cs
> +            RenderSimpleValues.RenderTexture("Texture", ref selectedConfiguration.horizonMask);
Several of these strings already exist at `unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/Editor/Procedural Skybox/SkyboxEditorLiterals.cs`, you could add the missing ones and reuse the ones that are already there

2022-05-18 09:48 UTC, AjimenezDCL commented
Closing this, because it's gonna be fixed here: https://github.com/decentraland/unity-renderer/pull/2324

2022-05-18 09:48 UTC, closed without merging