feat: throttled texture compression
decentraland/unity-renderer pull request #2287
Opened 2022-05-09 22:23 UTC by Kinerius

## What does this PR change?

For more info on how this works check #2283 comments.

## How to test the changes?

Open Decentraland WebGL and have fewer hiccups :) 

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2022-05-10 13:20 UTC, Kinerius commented
![image](https://user-images.githubusercontent.com/7646450/167637907-721de116-e7e7-4bc7-ae6e-20a3c5698591.png)

Copy texture not working on WebGL

2022-05-16 12:20 UTC, davidejensen reviewed
Walking around caused this to me, idk if it's related:
![Screenshot 2022-05-16 at 14 18 47](https://user-images.githubusercontent.com/4254522/168591068-4db263e3-7f6e-41ca-afbf-508d8abe40d4.png)

2022-05-16 14:03 UTC, Kinerius commented
> Walking around caused this to me, idk if it's related: ![Screenshot 2022-05-16 at 14 18 47](https://user-images.githubusercontent.com/4254522/168591068-4db263e3-7f6e-41ca-afbf-508d8abe40d4.png)

We still have some memory issues here and there, I'm pretty sure this PR isn't adding leaks but I can be wrong

2022-05-18 12:50 UTC, pravusjif requested changes
Found a problem that's most likely an issue with the CopyTexture:

https://user-images.githubusercontent.com/1031741/169042362-8ee28ffb-004a-4aee-9752-bf3ac7db81b2.mp4

That same problem was previously solved at https://github.com/decentraland/unity-renderer/pull/2012

2022-05-18 12:54 UTC, pravusjif commented
Also this scene images never finish compressing apparently (in master/prod they do):
![never-finishes](https://user-images.githubusercontent.com/1031741/169043351-ce2a1e8e-a24a-451c-94a5-34174a11f32e.png)

2022-05-19 08:55 UTC, AjimenezDCL requested changes

2022-05-19 08:55 UTC, AjimenezDCL commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/DCLTexture.cs
> +                        Debug.Log($"DCLTexture: {prev} -> {texture.format}");
Remove comment!

2022-05-19 08:55 UTC, AjimenezDCL commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromise.cs
> +            addToLibraryCoroutine = CoroutineUtils.StartThrottledCoroutine(AddToLibrary(OnAddToLibrary), OnLoadFailure, throttlingCounter.EvaluateTimeBudget);
We should stop any current coroutine on-going. Not sure how likely is that edge case, but it could lead to really nasty issues.

2022-05-19 08:55 UTC, AjimenezDCL commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/TextureResource/AssetPromise_TextureResource.cs
> +                        Debug.Log($"AssetPromise_TextureResource: {prev} -> {texture.format}");
Comment

2022-05-19 08:55 UTC, AjimenezDCL commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromise.cs
> +        protected virtual IEnumerator AddToLibrary(Action<bool> OnComplete)
IMO AddToLibrary should be an "atomic" method and not async/coroutine. It shouldnt also be capable of "failing" and the need of the callback should be removed.

We should be able to do the texture compression throttling when we retrieve the texture and leave all the flow as it is currently.

2022-05-19 22:19 UTC, Kinerius commented
The more I test this PR the more im convinced that this solution is only bringing downsides, im closing it for now.

2022-05-19 22:19 UTC, closed without merging