chore: update rider package
decentraland/unity-renderer pull request #2666
Opened 2022-07-20 08:22 UTC by AjimenezDCL

Update rider's package in Unity

# Test
This only affects editor

2022-07-20 12:17 UTC, aixaCode requested changes

2022-07-20 12:17 UTC, aixaCode commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/TeleportPromptHUDView.cs
> +    private HUDCanvasCameraModeController hudCanvasCameraModeController;
Is this is supposed to be part of this PR?

2022-07-20 15:18 UTC, aixaCode approved these changes
Why do we have all the changes with spaces?

2022-07-21 14:21 UTC, AjimenezDCL commented
@aixaCode > Why do we have all the changes with spaces?

My rider was autoformatting jsons, fixed it!

2022-07-29 08:28 UTC, merged