fix: optimizing PlayerName batching when it is turned off or turned on
decentraland/unity-renderer pull request #3046
Opened 2022-09-15 14:53 UTC by Antivortex

## What does this PR change?

This PR removed gameObject.SetActive calls from PlayerName class in methods responsible for showing and hiding the player names because of various reasons.

Closes #2713 

...

## How to test the changes?

Go with two peer avatar characters to the same area and check how the name of one character (over his head) is being shown and hidden from the perspective of other character during interactions like this:

1. Rotating camera when turning away from peer avatar character, then rotating back to him
2. Running away from the peer avatar character until his name disappears
3. Logging out on the peer avatar character side and seeing his name disappear together with him.
4. Teleporting peer avatar character and seeing his name disappear.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2022-09-21 11:47 UTC, kwspgoliasz approved these changes
The issue appears to be implemented correctly. Depending on the scenario, the username displayed above the avatar functions in the following manner:

1. When rotating the camera, the username goes out of the user's view in accordance with the camera angle. The username itself is fully visible at all times without fading out.
2. When moving away from the avatar, the username slowly fades out until disappearing completely.
3. When exiting the game or teleporting, the username disappears along with the avatar with no noticeable lags between the two.

2022-09-21 18:24 UTC, lorux0 requested changes

2022-09-21 18:24 UTC, lorux0 commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerName/Tests/PlayerNameShould.cs
> +        Assert.IsTrue(playerName.AllRenderersInvisible());
i dont like the exposure of `AllRenderersInvisible` method just for testing purposes. We are adding production functionality just for testing code. You should be able to check the alpha status of the internal `canvasRenderers` list from this test implementation

2022-09-27 07:55 UTC, kwspgoliasz approved these changes
The feature appears to be implemented correctly.

2022-09-27 10:26 UTC, Antivortex commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerName/PlayerName.cs
> +[assembly: InternalsVisibleTo("PlayerNameTests")]
@lorux0 
Turns out AssemblyInfo was already there for this assembly, so removing the reference from PlayerName was enough.

2022-09-27 13:20 UTC, lorux0 approved these changes

2022-09-27 14:15 UTC, merged