Feat: add unsupported bodyshape toast for wearables
decentraland/unity-renderer pull request #3082
Opened 2022-09-21 12:44 UTC by davidejensen

## What does this PR change?

Fix #2973 
Adds a small toast to give feedback on unusable wearables due to bodyshape

...

## How to test the changes?

1. Go to: https://play.decentraland.zone/?renderer-branch=feat/wearable-feedback
2. Open the backpack
3. Based on the body shape verify which wearables are grayed out and which not
4. Verify that hovering with the mouse shows the correct toast

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2022-09-22 11:22 UTC, kwspgoliasz requested changes
The feature appears to be implemented mostly correctly, however, a single issue with incorrectly marked section was found. When entering the backpack's body section, the unused avatar type is greyed out and marked as not compatible. Moreover, the icon color for the newly chosen avatar is regained only after switching tabs - https://user-images.githubusercontent.com/110464313/191733604-53607185-4f14-4c22-aaa1-8135cb452076.mp4.

Additionally, it might also be worth to grey out the entire item square and not only the item itself, as some wearables, especially black, white and grey ones, may visually be mistaken as available, despite being limited only to the other avatar type.

2022-09-22 13:55 UTC, Kinerius requested changes

2022-09-22 13:55 UTC, Kinerius commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/ItemToggle.cs
> +            if (!ShowReplacementWarningPanel())
This IF chain getting a bit hard to follow, I would refactor this just for clarity.

Something like
```C#
if (IsIncompatible())
{
    ShowIncompatibleWarning();
}
else if (IsGoingToReplaceSomething())
{
    ShowReplacementPanel();
}
else
{
    ShowHidingWarningPanel();
}
```
 
bool IsGoingToReplaceSomething

2022-09-23 13:00 UTC, kwspgoliasz approved these changes
The feature is implemented correctly and all of the issues reported to the owner of the PR were fixed.

2022-09-26 13:56 UTC, Kinerius approved these changes
LGTM! :D

2022-09-28 15:23 UTC, merged