Ab detection functionality
decentraland/unity-renderer pull request #3099
Opened 2022-09-23 15:49 UTC by Antivortex

## What does this PR change?

This PR:

1. Adds a tool for highlighting which mesh renderers are rendering the content loaded with asset bundles and which ones are loaded with raw GLTFs. DebugBridge receives a call from Kernel triggered by the chat command. This calls is passed to a ABDetectorPlugin via DataStore values as an intermediary. ABDetectorPlugin loads dedicated debug materials lazily on first call and applies them to the whole scene.
2. Adds custom low level data structure Multimap which is a generic wrapper for a dictionary of lists. After discussion with Alex we figured there are no class like that and decided to try using this one since it allows to not repeat a lot of code.

New chat commands are:

/detectabs => enable for all shapes
/detectabs off => disable for all shapes
/detectabs scene => enable for current scene shapes
/detectabs scene off => disable for current scene shapes (works only if "/decetabs scene" was used for this scene to enable)

...

## How to test the changes?

This PR has to be tested together with one Kernel PR that will be attached here later.

1. Use chat command `/detectabs ` at some place with ABs enabled. The shapes should turn green.
2. Use chat command `/detectabs off` . The shapes should turn to their usual look.
3. Use chat command `/detectabs scene` . The shapes should turn green only within current scene.
4. Use chat command `/detectabs scene off` . The shapes of that last scene should turn to their usual look.
5. Command `/detectabs off` should also turn all shapes to normal look after  `/detectabs scene`
6. Repeat 1-2 with ABs disabled, the color should be red instead of green.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2022-09-26 08:03 UTC, AjimenezDCL requested changes

2022-09-26 08:03 UTC, AjimenezDCL commented on unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DebugController/DebugBridge.cs
> +        private double _lastTimeDetectABsCalled;
```suggestion
        private double lastTimeDetectABsCalled;
```

2022-09-26 09:55 UTC, Antivortex commented on unity-renderer/Assets/DCLPlugins/EmoteAnimations/EmoteAnimationsPlugin.cs
> +        }
@AjimenezDCL 
I am used to break long lines to improve readability by fitting them into the screen with Explorer tab opened, but it's not  necessery, we can revert this file change.

2022-09-26 09:59 UTC, Antivortex commented on unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DebugController/DebugBridge.cs
> +            {
You're right, this is redundant in here

2022-09-26 10:10 UTC, Antivortex commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Multimap.cs
> +    public class Multimap<KT, VT>
Collection contains Keys property to return IEnumerable of keys and AllValues to return IEnumerable of all values to use LINQ on them. Do you suggest to implement IEnumerable<KeyValuePair<KT, List<VT>>> or something else?

2022-09-27 08:35 UTC, AjimenezDCL commented on unity-renderer/Assets/DCLPlugins/EmoteAnimations/EmoteAnimationsPlugin.cs
> +        }
Let's stick to what has been changed for the purpose of the PR. 

We usually dont break long lines, but I'm not against them. In any case, if you find a specific class hard to read, you can always create a small PR with these changes so we have better traceability of what's been changed and why without polluting the git log.

2022-09-27 08:37 UTC, AjimenezDCL approved these changes

2022-09-27 08:37 UTC, AjimenezDCL commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Multimap.cs
> +    public class Multimap<KT, VT>
that's probably enough, it is true that it wouldnt be much readable due to managing lists if we were to implement IEnumerable.

2022-09-27 09:39 UTC, merged