fix: Lazy Loading fixes
decentraland/unity-renderer pull request #3120
Opened 2022-09-26 16:26 UTC by sandrade-dcl

## What does this PR change?
Several fixes.

## How to test the changes?
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/lazy-loading-fixes
2. ...

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2022-09-29 16:05 UTC, lorux0 commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
> +                    onlineFriends.Remove(userId);
we should also consider to remove online friends on `FriendshipStatus.NOT_FRIEND` & `FriendshipStatus.REQUESTED_TO`

2022-09-30 14:44 UTC, kwspgoliasz requested changes
The feature appears to be implemented mostly correctly, however, several issues with the functionality of chat and friends are still present. The issues that were observed are:

1. User is not able to access a DM found with the search option - can be reproduced by searching for a DM from the channel menu: https://user-images.githubusercontent.com/110464313/193294276-ebe83de7-7364-4895-8628-81e04ff5d1a9.mp4.
2. The unfriended user is not correctly deleted from the friends list - changing the tab or closing and opening it makes the deleted friend reappear on the list. In most cases, the friend is visually on the list, however, clicking on the contextual menu gives an option to add a friend: https://user-images.githubusercontent.com/110464313/193294340-8b902013-f0b9-44a6-ad70-5d7af304f4ab.mp4.
3. The friends from other pages are loading on their own - the issue can be reproduced by opening the friends tab and waiting for about 1 minute. If the user has more than 30 friends, the issue will cause the entire friend list to load automatically: https://user-images.githubusercontent.com/110464313/193294374-30d44fa5-24f2-4616-a906-d519430e2bea.mp4.
4. Obsolete message regarding hidden chats in the chat menu - can be reproduced by going to the channel list section: 
![#3120](https://user-images.githubusercontent.com/110464313/193290585-7b501488-579c-4f6f-91a2-4f29e89d9c7c.jpg)

2022-10-04 19:26 UTC, lorux0 approved these changes

2022-10-04 19:30 UTC, sandrade-dcl commented
@kwspgoliasz could you please re-validate again? We have already applied the fixes:

> 1. User is not able to access a DM found with the search option - can be reproduced by searching for a DM from the channel menu: https://user-images.githubusercontent.com/110464313/193294276-ebe83de7-7364-4895-8628-81e04ff5d1a9.mp4.

✔️ Fixed!

> 2. The unfriended user is not correctly deleted from the friends list - changing the tab or closing and opening it makes the deleted friend reappear on the list. In most cases, the friend is visually on the list, however, clicking on the contextual menu gives an option to add a friend: https://user-images.githubusercontent.com/110464313/193294340-8b902013-f0b9-44a6-ad70-5d7af304f4ab.mp4.

✔️ Fixed!

> 3. The friends from other pages are loading on their own - the issue can be reproduced by opening the friends tab and waiting for about 1 minute. If the user has more than 30 friends, the issue will cause the entire friend list to load automatically: https://user-images.githubusercontent.com/110464313/193294374-30d44fa5-24f2-4616-a906-d519430e2bea.mp4.

✔️ Fixed!

> 4. Obsolete message regarding hidden chats in the chat menu - can be reproduced by going to the channel list section:
>    ![#3120](https://user-images.githubusercontent.com/110464313/193290585-7b501488-579c-4f6f-91a2-4f29e89d9c7c.jpg)

❓ We cannot reproduce it. Let us know if it is still happenning to you, but it wouldn't be a blocker.

2022-10-05 11:47 UTC, kwspgoliasz requested changes
The chat and friend features appear to be implemented mostly correctly. The basic features are functional and all of the problems mentioned in the previous comment were fixed. However, some additional issues were found during the retests:

- The DM chat history is not loaded for one user after accepting a friend request. The chat is only added after writing a new message to the friend. - https://user-images.githubusercontent.com/110464313/194051156-f8e9d7f1-eadb-468e-b071-f80856cf6c24.mp4.

- When accepting the invitation from the passport, the friend is added to the list with a noticeable delay for one user - https://user-images.githubusercontent.com/110464313/194051735-790111d0-3a19-4dd2-8c75-302f7264872a.mp4.

- In rare cases, after a friend is removed, the DM's and passport randomly do not register the update for one or both users. As a result, even though the friend was removed from the friend list, the user is described as friend in the passport. Moreover, even though the DM history is correctly deleted from the channel menu, the DM can still be accessed via the search feature. No stable repro was found for the issue, however, it seems more prone to occur, if there are at least four avatars are present in the area. After adding all of the avatars as friends and then removing them, the issue randomly occurs for one of the avatars located in the area.
![#3120_Friend](https://user-images.githubusercontent.com/110464313/194052177-efd2231f-9f18-411a-bc45-9bcc7da08601.jpg)

2022-10-05 13:26 UTC, kwspgoliasz approved these changes
The ticket is approved as the most severe issues were fixed. The newly found issues are to be addressed in another ticket.

2022-10-05 13:31 UTC, merged