fix: add wait for loading screen on teleport
decentraland/unity-renderer pull request #3164
Opened 2022-10-03 18:29 UTC by dalkia

## What does this PR change?

...

## How to test the changes?

1. Go to: https://play.decentraland.zone/?renderer-branch={branch_name}&{desired_url_params}
2. ...

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2022-10-04 07:57 UTC, AjimenezDCL requested changes
Left some comments, but it looks good

2022-10-04 07:57 UTC, AjimenezDCL commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Bridge/LoadingBridge.cs
> +    IEnumerator WaitForLoadingHUDVisible(string jsonMessage)
I'm not sure this is the place for this logic. Bridges should have no logic whatsoever, they should just put info in the datastore or call stuff.

In any case, this is temporary until we own full control of the loading flow in the renderer so we can let it pass through. In any case let's add comments and TODOs.

2022-10-04 07:57 UTC, AjimenezDCL commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs
> +using UnityEngine;
Please remove the formating/cleanup rearrangment of the code in this class.

It's hard to read the changes.

2022-10-13 08:30 UTC, AjimenezDCL approved these changes

2022-10-14 09:38 UTC, kwspgoliasz approved these changes
The feature appears to be implemented correctly. On the kernel branch, the empty camera flash was not observed when teleporting, or during the transition after the T&C.
When testing without the kernel branch, the issue with the empty camera returns for all of the teleportation methods. Regardless, the transition after T&C is functioning correctly even without the kernel branch.

2022-10-17 15:14 UTC, merged