feat: Implement toast to promote channels
decentraland/unity-renderer pull request #3358
Opened 2022-10-28 16:51 UTC by sandrade-dcl

## What does this PR change?
In order to show the new feature to players, we will implement a toast on top of the notification area with the next text:

"#channels have arrived! Now you can connect to global conversations of your favorite topics, or create your own."

Also, a "new" label will appear on top of the channels header inside the conversations panel.

### Acceptance Criteria
- Toast can be dismissed with a close icon
- Opening the chat icon will close the toast
- Toast will still appear in the next session until the player dismiss it
- After dissmiss, it wont appear anymore for that user.
- This toast is enabled via feature flag (`promote_channels_toast`)

## How to test the changes?
https://play.decentraland.zone/?renderer-branch=feat/promote-channels-toast

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2022-10-31 09:34 UTC, kwssbocian requested changes
Feature appears to be implemented mostly correctly.
✔️Toast is enabled via feature flag (promote_channels_toast).
✔️Toast can be dismissed with a close icon and after dismissing it wont appear anymore for that user.
✔️Opening the chat icon closes the toast.

Issue that has been found:
❌The toast is visible on the loading screen for the first time the client is launched with the feature branch. It is also visible in the character creation for a new account (including guest).
![toast](https://user-images.githubusercontent.com/110463715/198976032-179f7036-ea96-459a-9f75-bc03db3b59d4.png)
![toast2](https://user-images.githubusercontent.com/110463715/198976755-3ac40bd2-9bc1-49e2-93c2-8062b9355e39.png)

2022-10-31 15:04 UTC, lorux0 requested changes

2022-10-31 15:04 UTC, lorux0 commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PromoteChannelsToastComponentController.cs
> +            CommonScriptableObjects.rendererState.OnChange -= RendererState_OnChange;
you can inject `CommonScriptableObjects.rendererState` instead of the static usage

2022-10-31 15:04 UTC, lorux0 commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PromoteChannelsToastComponentController.cs
> +            if (!PlayerPrefsUtils.GetBool(PLAYER_PREFS_PROMOTE_CHANNELS_TOAS_DISMISSED_KEY, false))
you should inject `IPlayerPrefs` instead of the static usage

2022-10-31 15:04 UTC, lorux0 commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PromoteChannelsToastComponentController.cs
> +            PlayerPrefsUtils.SetBool(PLAYER_PREFS_PROMOTE_CHANNELS_TOAS_DISMISSED_KEY, true);
you should inject `IPlayerPrefs` instead of the static usage

2022-10-31 15:04 UTC, lorux0 commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PromoteChannelsToastComponentController.cs
> +            CommonScriptableObjects.rendererState.OnChange -= RendererState_OnChange;
you can inject `CommonScriptableObjects.rendererState` instead of the static usage

2022-10-31 15:04 UTC, lorux0 commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowComponentView.cs
> +        [SerializeField] private GameObject newLabel;
rename to `channelsPromoteLabel`

2022-10-31 15:24 UTC, lorux0 commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PromoteChannelsToastComponentController.cs
> +        public PromoteChannelsToastComponentController(
we are missing test coverage

2022-10-31 19:03 UTC, lorux0 approved these changes

2022-11-01 00:15 UTC, sandrade-dcl commented
> @sandrade-dcl here goes my comments.
> 
> <img alt="Screenshot 2022-10-31 at 16 39 07" width="643" src="https://user-images.githubusercontent.com/51088292/199095810-8a77954a-8948-48e9-a421-b3bba0885a4f.png">
> 
> 1- Adjust the pixels per unit in the close button container that looks too rounded. 2- Idem for the [new] label. This also applies for the label in the channels separator. 3- Tooltip background must be white. Currently looks light grey. 4- Reduce the gap between the tooltip and the social tab a half. 5- Aligned the tooltip with the social tab on the left.

@RominaMarchetti I already applied your requested changes. Only one thing: about the point 5 ("Aligned the tooltip with the social tab on the left"), I think it looks worse now because the bottom arrow doesn't coincide with the chat button in the taskbar:

![image](https://user-images.githubusercontent.com/64659061/199132015-90c9f2f3-dd21-485f-b489-16084473bf7e.png)

I think it is happening because the taskbar drawed in Figma is a bit different to the real one. In my opinion it looks better if we move the toast a bit to the left. Something like this:

![image](https://user-images.githubusercontent.com/64659061/199132082-0d22fee8-172c-438b-9120-aad88fb4004f.png)

If we want to make the toast margin coincide with the taskbar one we should modify the toast image to move the arrow a bit to the left, or modify the taskbar in order to make it coincide with figma.

2022-11-01 12:19 UTC, RominaMarchetti commented
Got it @sandrade-dcl 👍

2022-11-01 12:19 UTC, RominaMarchetti approved these changes

2022-11-02 10:56 UTC, kwssbocian approved these changes
Requested changes appear to have been implemented correctly.
✔️Visual fixes for the toast have been applied as agreed. Close button has been adjusted and now looks less rounded. Tooltip background is white. Gap between tooltip and social tab has been reduced.
✔️The toast no longer appears in the loading menu or the initial character creation.

2022-11-02 12:34 UTC, merged