fix: add global inputs and process multiple input in one tick
decentraland/unity-renderer pull request #3973
Opened 2023-01-11 19:34 UTC by leanmendoza

## What does this PR change?

Fix https://github.com/decentraland/sdk/issues/546
Fix https://github.com/decentraland/sdk/issues/550

## How to test the changes?

You can test each issue with https://playground.decentraland.org/?&renderer-branch=fix/global-and-multiple-button-events , then paste the snippet.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2023-01-12 14:15 UTC, pbosio requested changes
looks good! 
some small changes requested

2023-01-12 14:15 UTC, pbosio commented on unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_ECS7.cs
> +        public bool[] lastButtonState = new bool[MAX_BUTTON];
this should be moved to `ECSPointerInputSystem` state, ideally we should use data store only for stuffs that are needed from outside sdk7 responsibility

2023-01-12 14:15 UTC, pbosio commented on unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_ECS7.cs
> +        public bool[] buttonState = new bool[MAX_BUTTON];
```suggestion
        public readonly bool[] buttonState = new bool[Enum.GetValues(typeof(WebInterface.ACTION_BUTTON)).Length];
```

2023-01-12 14:15 UTC, pbosio commented on unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECSPointerInputSystem.cs
>              }
```suggestion
            } 
```

2023-01-12 15:08 UTC, pbosio approved these changes

2023-01-12 17:22 UTC, Kinerius approved these changes
Nice refactor!

2023-01-12 17:22 UTC, Kinerius commented on unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECSPointerInputSystem.cs
> +            // 1) We were hitting a collider A and now we're hitting a collider B
Could we get those steps extracted into methods? so we can reduce the visual complexity of this whole Update function.

2023-01-12 17:22 UTC, Kinerius commented on unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECSPointerInputSystem.cs
> +            // 1) We were hitting a collider A and now we're hitting a collider B
### Example
```C#
if (IsColliderDifferent(state))
{
    HandleColliderChanged(state);
} 
if (IsColliderMissing(state))
{ 
    HandleMissingCollider(state);
}
if (IsColliderAvailable(state))
{
    HandleAvailableCollider(state)
} 
```

2023-01-16 15:10 UTC, kwssbocian approved these changes
Issues appear to be fixed.
✔️Global and targeted action spheres/boxes respond correctly to the issued commands and disappear upon having the action triggered.
✔️Global inputs are registered regardless of direction the player is looking in.
✔️Multiple simultaneous inputs are correctly being registered.

2023-01-17 18:39 UTC, merged