Fix: castShadows property not working
decentraland/unity-renderer pull request #4081
Opened 2023-01-19 16:43 UTC by 0xD-Fabio

## What does this PR change?

...

## How to test the changes?

1. Go to: https://play.decentraland.zone/?renderer-branch={branch_name}&{desired_url_params}
2. ...

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2023-01-25 20:50 UTC, pbosio approved these changes
LGTM

2023-01-26 09:44 UTC, davidejensen approved these changes

2023-01-26 11:01 UTC, 0xD-Fabio commented on unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_WorldObjects.cs
> +            public readonly BaseHashSet<Renderer> renderers = new BaseHashSet<Renderer>(); // FD:: test caching renderers
ops sorry, slipped comment

2023-01-26 13:56 UTC, Kinerius requested changes
The original bug of the castShadows is still not fixed

https://github.com/decentraland/unity-renderer/issues/3533

![image](https://user-images.githubusercontent.com/7646450/214853761-b6e76f5d-ccee-4874-9175-a43d8cba560a.png)

2023-01-26 18:12 UTC, Kinerius approved these changes

2023-01-26 18:18 UTC, merged