Add sentry plugin to enrich events
decentraland/unity-renderer pull request #4090
Opened 2023-01-20 10:28 UTC by m3taphysics

Enrich sentry reports with the following data:

1. Realm
2. Player Current / Previous Position
3. Last / Previous Teleport Positions
4. Total Other Player Count

2023-01-20 10:58 UTC, mikhail-dcl requested changes

2023-01-20 10:58 UTC, mikhail-dcl commented on unity-renderer/Assets/DCLPlugins/SentryPlugin/SentryPlugin.cs
> +            scope.SetExtra("Current Teleport Position", $"{current.x},{current.y}");
They say `SetExtra` is deprecated nowadays so we need to use named contexts https://docs.sentry.io/platforms/unity/enriching-events/context/

2023-01-23 12:31 UTC, mikhail-dcl requested changes

2023-01-23 12:31 UTC, mikhail-dcl commented on unity-renderer/Assets/DCLPlugins/SentryPlugin/SentryController.cs
> +        public SentryController(DataStore_Player playerStore, DataStore_Realm realmStore, IHub sentryHub)
Please apply Code clean-up: it will add some extra spacing in your files

2023-01-23 12:31 UTC, mikhail-dcl commented on unity-renderer/Assets/DCLPlugins/SentryPlugin/SentryPlugin.cs
> +public class SentryPlugin : IPlugin
Please move it to the namespace

2023-01-23 12:31 UTC, mikhail-dcl commented on unity-renderer/Assets/DCLPlugins/SentryPlugin/Tests/SentryControllerTests.cs
> +            var sentryHubMock = Substitute.For<IHub>();
You could move all configuring logic to the `[Setup]` method. It would sanitize the logic of the tests themselves.

2023-01-23 13:10 UTC, mikhail-dcl approved these changes

2023-01-23 20:50 UTC, Kinerius approved these changes
Looks good to me, also I fixed the compilation error :)

2023-01-24 09:30 UTC, merged