feat: change crdt executor and serialization (adr-117 rev. 2)
decentraland/unity-renderer pull request #4099
Opened 2023-01-20 23:43 UTC by leanmendoza

wip

## What does this PR change?

...

## How to test the changes?

1. Go to: https://play.decentraland.zone/?renderer-branch={branch_name}&{desired_url_params}
2. ...

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2023-01-25 17:59 UTC, pbosio approved these changes

2023-01-25 17:59 UTC, pbosio commented on unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/SceneControllerServiceImpl.cs
> +                    }
```suggestion
                    for (int i = 0; i < sceneCrdtOutgoing.Count; i++)
                    {
                        CRDTSerializer.Serialize(sendCrdtBinaryWriter, sceneCrdtOutgoing.Pairs[i].value);
                    }
```

2023-02-02 11:08 UTC, kwssbocian approved these changes
Feature implemented correctly.
✔️No changes in behavior for playground launched with and without query parameters.

2023-02-06 13:11 UTC, Kinerius approved these changes

2023-02-06 13:17 UTC, AjimenezDCL requested changes

2023-02-06 14:10 UTC, pbosio commented on unity-renderer/Assets/DCLPlugins/ECS7/ComponentCrdtWriteSystem/ComponentCrdtWriteSystem.cs
> +    private readonly Dictionary<int, DualKeyValueSet<int, long, CRDTMessage>> outgoingCrdt = new Dictionary<int, DualKeyValueSet<int, long, CRDTMessage>>(60);
It works kind of like a [sparse set](https://manenko.com/2021/05/23/sparse-sets.html)
every element is added to a list and have a dictionary to map `id => list index` to get or remove individual elements
making this data structure under-perform a dictionary when adding a element and heavily under-perform a dictionary when removing an element, but it much faster than a dictionary when iterating through all it's elements

2023-02-06 14:31 UTC, AjimenezDCL commented on unity-renderer/Assets/DCLPlugins/ECS7/ComponentCrdtWriteSystem/ComponentCrdtWriteSystem.cs
> +    private readonly Dictionary<int, DualKeyValueSet<int, long, CRDTMessage>> outgoingCrdt = new Dictionary<int, DualKeyValueSet<int, long, CRDTMessage>>(60);
You are right, I created a small benchmark for this: 
![image](https://user-images.githubusercontent.com/50231608/216998302-93718005-1c71-4dd7-ae2b-c1d0c2d8d11a.png)


I guess the outgoingCrdt buffer will be big enough to make this noticeable

2023-02-06 14:31 UTC, AjimenezDCL approved these changes

2023-02-06 17:31 UTC, pbosio approved these changes

2023-02-06 18:11 UTC, merged