Chore: removed unused OnGUI event dispatcher
decentraland/unity-renderer pull request #4278
Opened 2023-02-06 11:09 UTC by davidejensen

## What does this PR change?

Removes unused dispatcher of OnGUI events to remove memory allocation.
Each usage of OnGUI (even if an empty function), allocates around 360B of GC per frame. 

Before the change:
<img width="1727" alt="Screenshot 2023-02-06 at 12 09 12" src="https://user-images.githubusercontent.com/4254522/216956574-d612f781-7419-428f-8133-82e5c2ffe5f7.png">

After the change:
<img width="1727" alt="Screenshot 2023-02-06 at 12 07 23" src="https://user-images.githubusercontent.com/4254522/216956247-62df78a8-46b4-4e68-b6af-850a2e8d0265.png">

2023-02-06 11:11 UTC, AjimenezDCL requested changes
Remove also `IUpdateEventHandler.EvenType.OnGui` and any dangling usage.

2023-02-06 11:16 UTC, davidejensen commented
> Remove also `IUpdateEventHandler.EvenType.OnGui` and any dangling usage.

Done, it was never used, removed the definition

2023-02-07 09:21 UTC, AjimenezDCL approved these changes

2023-02-07 19:32 UTC, dalkia approved these changes
Nice cleanup!

2023-02-08 09:53 UTC, merged