Chore: simple refactor to unify places requests
decentraland/unity-renderer pull request #4638
Opened 2023-03-15 16:08 UTC by davidejensen

## What does this PR change?

...

## How to test the changes?

1. Launch the explorer
2. ...

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2023-04-07 14:30 UTC, mikhail-dcl requested changes
You should resolve all the conflicts first before we can really review it as there were too many changes from the new map renderer

2023-04-11 12:43 UTC, mikhail-dcl requested changes

2023-04-11 12:44 UTC, davidejensen commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IPutWebRequestFactory.cs
> +        void SetPatchRequest(bool isPatchRequest);
we can if you prefer, I did it like this because UnityRequests do not have support for Patch requests and they treat them as PUT requests

2023-04-12 13:26 UTC, mikhail-dcl approved these changes

2023-04-14 09:29 UTC, sandrade-dcl approved these changes

2023-04-14 09:29 UTC, sandrade-dcl commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/PlacesSubSection/FavoritesSubSection/FavoritesesSubSectionComponentController.cs
>  public class FavoritesesSubSectionComponentController : IFavoritesSubSectionComponentController, IPlacesAndEventsAPIRequester
Is this a typo? Shouldn't this class be called `FavoritesSubSectionComponentController`?

2023-04-14 09:31 UTC, sandrade-dcl commented
@davidejensen One question: Is the normal mehaviour, when you set a favorite place and you go to FAVORITES section, that the corresponding place doesn't disappear from the section after you click on un-favorite and you have to go out of the section and re-enter again to see this place was removed?

2023-05-10 10:26 UTC, merged