fix: gpuSkinningThrottlerService.Register() called twice
decentraland/unity-renderer pull request #4759
Opened 2023-03-27 21:13 UTC by popuz

## What does this PR change?

Avatar was registering its `gpuSkinning `each time when calling `Load() `method. This cause the problem, since gpuSkinning instance is readonly assigned on Avatar creation, but `Load `called often - for example by `CharacterPreviewController` when changing wearables from backpack.

- added simple flag to not register again when calling Load method
- extended Log inside Throtller with more info

[Devs Only]
1. Launch the explorer
2. Change wearables in Backpack
3. Observe no LogWarning in console from `gpuSkinningThrottlerService`

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2023-03-29 08:35 UTC, AjimenezDCL requested changes

2023-03-29 08:35 UTC, AjimenezDCL commented on unity-renderer/Assets/Rendering/Utils/GPUSkinning/GPUSkinningThrottlerService.cs
> +            Debug.LogWarning($"GPUSkinningThrottlerService: Register called twice for the same IGPUSkinning {gpuSkinning}", gpuSkinning.renderer.gameObject);
I'd remove this warning and instead just modify the current throttling.

2023-03-29 08:36 UTC, AjimenezDCL requested changes

2023-03-30 08:20 UTC, AjimenezDCL approved these changes

2023-03-30 21:50 UTC, dalkia commented
Really like the refactor used in `Avatar` and `AvatarWithHologram`! Nice use of the Template method. As much we can save on those convuleted class, the better.

`gpuSkinningThrottlerService` is not being called twice, but the PR introduced a visual regression. Other players are in T position before appearing, instead of idle

PR
<img width="1728" alt="Screen Shot 2023-03-30 at 18 43 42" src="https://user-images.githubusercontent.com/1999557/228972254-93afd0dd-71c6-4397-a917-a68182f80614.png">

PRD
<img width="1728" alt="Screen Shot 2023-03-30 at 18 45 09" src="https://user-images.githubusercontent.com/1999557/228972268-dee40c60-ce79-4052-9700-fd4a51c3b5bc.png">

2023-03-31 14:50 UTC, dalkia approved these changes

2023-04-04 09:58 UTC, kwsskulinski approved these changes
No issues have been found.

2023-04-04 10:28 UTC, merged