fix: fixed colore reset for notifications with mention
decentraland/unity-renderer pull request #4790
Opened 2023-03-29 09:19 UTC by davidejensen

## What does this PR change?

Fix #4786
Avoids pooled messages to appear yellow when no mention is detected

...

## How to test the changes?

1. Launch the explorer
2. Send 30+ messages with mentions from a second account
3. Verify that after the 30 messages by sending regular messages without mentions the background is white and not yellow

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2023-03-31 08:10 UTC, mikhail-dcl requested changes

2023-03-31 08:10 UTC, mikhail-dcl commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DefaultChatEntry.cs
> +                backgroundImage.color = Color.white;
it is a good point: we need to take the current color from `Image` as we can't guarantee it's `white`

2023-03-31 14:19 UTC, davidejensen commented on unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DefaultChatEntry.cs
> +                backgroundImage.color = Color.white;
Good point, done!

2023-03-31 19:13 UTC, lorux0 approved these changes

2023-04-03 11:56 UTC, mikhail-dcl approved these changes

2023-04-03 12:23 UTC, merged