chore: upload code coverage report
decentraland/unity-renderer pull request #777
Opened 2021-07-07 14:22 UTC by kuruk-mm

Fix #700
## What does this PR change?

- Add code coverage package to Unity
- Upload code coverage report to S3
- Now GitHub Bot to comment the link of the report

Maybe this would be an intermediate step to upload the code coverage to a service like http://coveralls.io/.

## How to test the changes?

1. Go to the bot comment on this PR
2. See if it reported the code coverage and if you can see it well.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2021-07-07 17:05 UTC, menduz commented
Beautiful

2021-07-07 17:07 UTC, menduz approved these changes

2021-07-08 08:43 UTC, AjimenezDCL commented
Graet!

2021-07-08 08:43 UTC, AjimenezDCL approved these changes

2021-07-08 16:50 UTC, BrianAmadori requested changes
We should exclude the following assemblies from the coverage:

- Protobuf generated code
- The websocket library assemblies (as its external)
- GLTF importer assemblies (as its external).

Now, the `ABConverted` assembly was also removed on the original coverage assessment because the tests are editor-only and we don't have that integrated in the pipeline. We can leave this as is for now as a reminder I think.

2021-07-08 19:57 UTC, BrianAmadori approved these changes

2021-07-08 19:59 UTC, merged